// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfx3eW9eelsaIk045ioj8sVIVgGZvR9E',
    appId: '1:483796313572:web:84b908ed1705d8cbbe53f1',
    messagingSenderId: '483796313572',
    projectId: 'vkr-bff',
    authDomain: 'vkr-bff.firebaseapp.com',
    storageBucket: 'vkr-bff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlphKVm2SpuWGW5W63FZu9pq09rmVusmY',
    appId: '1:483796313572:android:7c5bcfabd0130184be53f1',
    messagingSenderId: '483796313572',
    projectId: 'vkr-bff',
    storageBucket: 'vkr-bff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaMRpHgDXA-P1ZNUp-4fx6VFioqE87q0',
    appId: '1:483796313572:ios:b1b1f508866383f0be53f1',
    messagingSenderId: '483796313572',
    projectId: 'vkr-bff',
    storageBucket: 'vkr-bff.firebasestorage.app',
    iosBundleId: 'com.example.vkrTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCfx3eW9eelsaIk045ioj8sVIVgGZvR9E',
    appId: '1:483796313572:web:9d5290914c18bf8abe53f1',
    messagingSenderId: '483796313572',
    projectId: 'vkr-bff',
    authDomain: 'vkr-bff.firebaseapp.com',
    storageBucket: 'vkr-bff.firebasestorage.app',
  );
}
